name = "gg-samachar"
main = "worker.js"
compatibility_date = "2026-09-28"

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = [
  "/api/*",
  "/collect",
  "/collect-now",
  "/admin/*"
]

[[d1_databases]]
binding = "DB"
database_name = "gg-samachar-db"
database_id = "ca9bd599-b199-4acf-89be-19de97f3d0b1"

[triggers]
crons = ["*/30 * * * *"]
