name = "gg-samachar-api"
main = "worker.js"
compatibility_date = "2026-09-28"

[[d1_databases]]
binding = "DB"
database_name = "gg-samachar-db"
database_id = "9520174b-236c-48b9-baa0-1ee16fdf6cb4"

[triggers]
crons = ["0 * * * *"]
