const API="https://gg-samachar.rahulsocialwits.workers.dev";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let token=sessionStorage.gg_admin_session||"",data={};

const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const headers=()=>({"Content-Type":"application/json",...(token?{"Authorization":"Bearer "+token}:{})});
async function req(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...headers(),...(opt.headers||{})}});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||"HTTP "+r.status);return j}
function badge(ok,label){return '<span class="health '+(ok?'good':'bad')+'">● '+esc(label)+'</span>'}
function showPage(name){$$(".page").forEach(x=>x.classList.toggle("active",x.id===name));$$(".sidebar nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===name));$("#pageTitle").textContent=name==="create"?"Create / Edit Article":name[0].toUpperCase()+name.slice(1);({dashboard:renderDashboard,articles:renderArticles,create:renderCreate,sources:renderSources,automation:renderAutomation,diagnostics:renderDiagnostics,settings:renderSettings}[name]||renderDashboard)()}
async function refresh(){data=await req("/admin/data");return data}
async function boot(){try{await refresh();$("#loginGate").hidden=true;$("#app").hidden=false;showPage("dashboard")}catch(e){$("#loginMsg").textContent=e.message;sessionStorage.removeItem("gg_admin_session");token=""}}
$("#toggleKey").onclick=()=>{const i=$("#loginPassword"),b=$("#toggleKey"),show=i.type==="password";i.type=show?"text":"password";b.textContent=show?"Hide":"Show"};
$("#loginBtn").onclick=async()=>{const email=$("#loginEmail").value.trim(),password=$("#loginPassword").value;if(!email||!password){$("#loginMsg").textContent="Enter email and password.";return}$("#loginMsg").textContent="Signing in…";try{const r=await fetch(API+"/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})}),j=await r.json();if(!r.ok)throw Error(j.error||"Login failed");token=j.token;sessionStorage.gg_admin_session=token;$("#loginPassword").value="";$("#loginMsg").textContent="";await boot()}catch(e){token="";sessionStorage.removeItem("gg_admin_session");$("#loginMsg").textContent=e.message}};
$("#loginEmail,#loginPassword").forEach(x=>x.onkeydown=e=>{if(e.key==="Enter")$("#loginBtn").click()});
$("#logout").onclick=async()=>{try{await req("/admin/logout",{method:"POST"})}catch{}sessionStorage.removeItem("gg_admin_session");location.reload()};
$$(".sidebar nav button").forEach(b=>b.onclick=()=>showPage(b.dataset.page));

function statCard(value,label){return '<div class="stat-card"><b>'+Number(value||0)+'</b><span>'+esc(label)+'</span></div>'}
function renderDashboard(){
 const s=data.stats||{},last=data.last_run,health=data.source_health||[];
 $("#dashboard").innerHTML='<div class="hero"><div><small>NEWS ENGINE</small><h2>Gujarati newsroom control center</h2><p>RSS → validation → optional Groq → D1 → website.</p></div><div class="hero-actions"><button class="primary" id="fetchNow">⚡ Fetch News Now</button><button class="ghost" id="diagNow">Run Health Check</button></div></div>'+
 '<div class="stats">'+statCard(s.total,"Total Articles")+statCard(s.published,"Published")+statCard(s.drafts,"Drafts")+statCard(s.with_images,"With Images")+'</div>'+
 '<div class="status-grid"><div class="panel"><div class="panel-head"><h2>Source Health</h2><button class="ghost" onclick="showPage(\'sources\')">Manage →</button></div>'+health.map(x=>'<div class="health-row"><span><b>'+esc(x.name)+'</b><small>'+esc(x.error||("Last check: "+x.checked_at))+'</small></span>'+badge(x.status==="ok",x.status==="ok"?"Healthy":"Failed")+'</div>').join("")+'</div>'+
 '<div class="panel"><div class="panel-head"><h2>Last Automation</h2></div>'+(last?'<div class="big-number">'+esc(last.published)+' <small>published</small></div><p>'+esc(last.message||"")+'</p><p class="muted">'+esc(last.run_at)+'</p>':'<div class="empty">No collection run yet.</div>')+'</div></div>'+
 '<div class="panel"><div class="panel-head"><h2>Latest Articles</h2><button class="ghost" onclick="showPage(\'articles\')">Manage all →</button></div>'+articleTable((data.articles||[]).slice(0,10))+'</div>';
 $("#fetchNow").onclick=fetchNow;$("#diagNow").onclick=()=>showPage("diagnostics");
}
function articleTable(arr){if(!arr.length)return'<div class="empty">No articles yet.</div>';return '<div class="table-wrap"><table><thead><tr><th>Article</th><th>Category</th><th>Source</th><th>Image</th><th>Status</th><th>Action</th></tr></thead><tbody>'+arr.map(a=>'<tr><td><b>'+esc(a.title_gujarati)+'</b><small>'+esc(a.title_english||"")+'</small></td><td>'+esc(a.category||"—")+'</td><td>'+esc(a.source_name||"—")+'</td><td>'+(a.image_url?'<img class="thumb" src="'+esc(a.image_url)+'">':'—')+'</td><td><span class="badge">'+esc(a.status||"published")+'</span></td><td><button class="small" onclick="editArticle('+a.id+')">Edit</button> <button class="small danger" onclick="deleteArticle('+a.id+')">Delete</button></td></tr>').join("")+'</tbody></table></div>'}
function renderArticles(){$("#articles").innerHTML='<div class="section-head"><div><small>CONTENT MANAGEMENT</small><h2>Articles</h2><p>Search, edit, publish or remove newsroom stories.</p></div><button class="primary" onclick="showPage(\'create\')">＋ New Article</button></div>'+articleTable(data.articles||[])}
function formHTML(a={}){return '<div class="panel editor"><div class="form-grid"><label>Gujarati Title<input id="f_gu" value="'+esc(a.title_gujarati||"")+'"></label><label>English Title<input id="f_en" value="'+esc(a.title_english||"")+'"></label><label>Category<select id="f_cat"><option>Gujarat</option><option>India</option><option>World</option><option>Business</option><option>Sports</option><option>Entertainment</option><option>Technology</option></select></label><label>City<input id="f_city" value="'+esc(a.city||"")+'" placeholder="Ahmedabad"></label></div><label>Gujarati Summary<textarea id="f_sg" rows="3">'+esc(a.summary_gujarati||"")+'</textarea></label><label>English Summary<textarea id="f_se" rows="3">'+esc(a.summary_english||"")+'</textarea></label><label>Gujarati Content<textarea id="f_cg" rows="10">'+esc(a.content_gujarati||"")+'</textarea></label><label>English Content<textarea id="f_ce" rows="10">'+esc(a.content_english||"")+'</textarea></label><div class="form-grid"><label>Image URL<input id="f_img" value="'+esc(a.image_url||"")+'" placeholder="https://..."></label><label>Status<select id="f_status"><option>published</option><option>draft</option></select></label></div><label>SEO Description<textarea id="f_seo" rows="2">'+esc(a.seo_description||"")+'</textarea></label><button class="primary" id="saveArticle">Save Article</button><div id="formMsg"></div></div>'}
function values(){return{title_gujarati:$("#f_gu").value,title_english:$("#f_en").value,category:$("#f_cat").value,city:$("#f_city").value,summary_gujarati:$("#f_sg").value,summary_english:$("#f_se").value,content_gujarati:$("#f_cg").value,content_english:$("#f_ce").value,image_url:$("#f_img").value,status:$("#f_status").value,seo_description:$("#f_seo").value}}
function renderCreate(a={}){$("#create").innerHTML='<div class="section-head"><div><small>EDITOR</small><h2>'+esc(a.id?"Edit Article #"+a.id:"Create Article")+'</h2></div><button class="ghost" onclick="showPage(\'articles\')">← Back</button></div>'+formHTML(a);$("#f_cat").value=a.category||"Gujarat";$("#f_status").value=a.status||"published";$("#saveArticle").onclick=async()=>{try{await req(a.id?"/admin/articles/"+a.id:"/admin/articles",{method:a.id?"PUT":"POST",body:JSON.stringify(values())});await refresh();showPage("articles")}catch(e){$("#formMsg").textContent=e.message}}}
window.editArticle=id=>{const a=(data.articles||[]).find(x=>x.id===id);if(a)renderCreate(a)};
window.deleteArticle=async id=>{if(!confirm("Delete this article?"))return;try{await req("/admin/articles/"+id,{method:"DELETE"});await refresh();showPage("articles")}catch(e){alert(e.message)}};
function renderSources(){const s=data.sources||[],h=Object.fromEntries((data.source_health||[]).map(x=>[x.source_id,x]));$("#sources").innerHTML='<div class="section-head"><div><small>SOURCE MANAGEMENT</small><h2>News Sources</h2><p>D1 is the single source of truth for enabled feeds.</p></div><button class="primary" onclick="addSource()">＋ Add Source</button></div><div class="source-grid">'+s.map(x=>{const z=h[x.id];return '<div class="source"><div class="source-top"><b>'+esc(x.name)+'</b>'+badge(!!x.enabled,x.enabled?"Enabled":"Disabled")+'</div><small>'+esc(x.feed_url||"")+'</small><p class="muted">'+esc(z?.status==="ok"?"Last test "+z.latency_ms+"ms":(z?.error||"Not tested"))+'</p><div class="source-actions"><button class="small" onclick="testSource('+x.id+')">Test</button><button class="small" onclick="toggleSource('+x.id+','+(!x.enabled)+')">'+(x.enabled?"Disable":"Enable")+'</button></div></div>'}).join("")+'</div>'}
window.addSource=async()=>{const name=prompt("Source name");if(!name)return;const feed=prompt("RSS/Atom feed URL");if(!feed)return;try{await req("/admin/sources",{method:"POST",body:JSON.stringify({name,feed_url:feed})});await refresh();renderSources()}catch(e){alert(e.message)}};
window.testSource=async id=>{try{const r=await req("/admin/test-source",{method:"POST",body:JSON.stringify({id})});alert(r.ok?"Source OK · "+r.items+" items · "+r.latency_ms+"ms":r.error||("HTTP "+r.status))}catch(e){alert(e.message)}};
window.toggleSource=async(id,enabled)=>{try{await req("/admin/source-toggle",{method:"POST",body:JSON.stringify({id,enabled})});await refresh();renderSources()}catch(e){alert(e.message)}};
function renderAutomation(){const l=data.logs||[];$("#automation").innerHTML='<div class="section-head"><div><small>AUTOMATION</small><h2>Automation & Logs</h2><p>Every Cron/manual run is recorded here.</p></div><button class="primary" onclick="fetchNow()">⚡ Run Now</button></div><div class="panel">'+(l.length?'<div class="table-wrap"><table><thead><tr><th>Run</th><th>Fetched</th><th>Published</th><th>Skipped</th><th>Errors</th><th>Message</th></tr></thead><tbody>'+l.map(x=>'<tr><td>'+esc(x.run_at)+'</td><td>'+x.fetched+'</td><td>'+x.published+'</td><td>'+x.skipped+'</td><td>'+x.errors+'</td><td>'+esc(x.message)+'</td></tr>').join("")+'</tbody></table></div>':'<div class="empty">No automation runs yet.</div>')+'</div>'}
async function renderDiagnostics(){let d;try{d=await req("/admin/diagnostics")}catch(e){$("#diagnostics").innerHTML='<div class="empty">'+esc(e.message)+'</div>';return}const s=d.services||{};$("#diagnostics").innerHTML='<div class="section-head"><div><small>SYSTEM HEALTH</small><h2>Diagnostics</h2><p>Real provider checks, not just configuration flags.</p></div><button class="primary" onclick="renderDiagnostics()">↻ Refresh</button></div><div class="health-cards">'+[['Cloudflare Worker',s.cloudflare_worker],['D1 Database',s.d1],['Groq AI',s.groq],['Weather API',s.weather],['Market API',s.market]].map(([n,x])=>'<div class="panel"><b>'+esc(n)+'</b><div class="diag-status">'+badge(x?.ok,x?.ok?"Healthy":"Failed")+'</div><small>Status: '+esc(x?.status??"—")+' · '+esc(x?.latency_ms??"—")+'ms</small></div>').join("")+'</div><div class="panel"><h3>Last Cron Run</h3><pre>'+esc(JSON.stringify(d.cron||{},null,2))+'</pre></div>'}
function renderSettings(){$("#settings").innerHTML='<div class="section-head"><div><small>SYSTEM</small><h2>Settings</h2></div></div><div class="settings-grid"><div class="panel"><b>API</b><p>'+API+'</p><span>Cloudflare Worker · D1</span></div><div class="panel"><b>AI</b><p>Groq</p><span>Optional rewriting; feed publication continues if AI fails.</span></div><div class="panel"><b>Weather</b><p>Open-Meteo currently wired</p><span>Provider diagnostics included.</span></div><div class="panel"><b>Market</b><p>Snapdata + TejHQ snapshot</p><span>Current feed is daily reference data, not guaranteed intraday.</span></div><div class="panel"><b>Calendar</b><p>Shastra Panchangam</p><span>Dynamic Panchang endpoint.</span></div><div class="panel"><b>Schedule</b><p>Every 30 minutes</p><span>Cloudflare Cron Trigger.</span></div></div>'}
async function fetchNow(){try{const r=await req("/admin/collect",{method:"POST"});await refresh();alert("Collection complete · "+r.published+" published · "+r.errors+" errors");showPage("dashboard")}catch(e){alert("Collection failed: "+e.message)}}
if(token)boot();